In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/aksharantardataset/aksharantar_sampled/brx/brx_test.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/brx/brx_valid.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/brx/brx_train.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/tam/tam_valid.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/tam/tam_train.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/tam/tam_test.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/mni/mni_valid.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/mni/mni_test.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/mni/mni_train.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/urd/urd_train.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/urd/urd_valid.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/urd/urd_test.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/kok/kok_valid.csv
/kaggle/input/aksharantardataset/aksharantar_sampled/kok/kok_train.csv
/kaggle/in

In [ ]:
!pip install torchvision
import torch.nn as nn
import torch.nn.functional as func
import torch.optim as optim
import torch.utils.data as data
from torchvision import datasets,transforms
import numpy as np
import matplotlib.pyplot as plt
import math
import torch
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
import pandas as pd
import random

In [ ]:
from tqdm import tqdm
#device selection CPU or GPU
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [ ]:
train_data_root='/kaggle/input/aksharantardataset/aksharantar_sampled/tel/tel_train.csv'
valid_data_root='/kaggle/input/aksharantardataset/aksharantar_sampled/tel/tel_valid.csv'
test_data_root='/kaggle/input/aksharantardataset/aksharantar_sampled/tel/tel_test.csv'

In [ ]:
train_data=pd.read_csv(train_data_root,header=None)
valid_data=pd.read_csv(valid_data_root,header=None)
test_data=pd.read_csv(test_data_root,header=None)
print(train_data[0][1])
eng_list_train=train_data[0]
tel_list_train=train_data[1]
eng_list_valid=valid_data[0]
tel_list_valid=valid_data[1]
eng_list_test=test_data[0]
tel_list_test=test_data[1]
print(tel_list_train)

vastadira
0              వర్గాలవారినే
1                 వస్తాదిరా
2             ఫ్యాక్టమ్ఫోస్
3                మూత్రనాళాల
4                 ద్విపాత్ర
                ...        
51195          తెలుస్తోందవి
51196               పేచింగ్
51197    వెనక్కితీసుకోవాలనే
51198            రూపాంతరాలు
51199           చెందిందింది
Name: 1, Length: 51200, dtype: object


In [ ]:
eng_vocab=[] #list of the letters in the english words
tel_vocab=[] #list of the letters in the telugu words
max_eng_len=-1
max_tel_len=-1
max_eng_word=""
max_tel_word=""
for word in eng_list_train:
    max_eng_len=max(max_eng_len,len(word))
    if(max_eng_len==len(word)):
        max_eng_word=word
    for letter in word:
        eng_vocab.append(letter)
eng_vocab=list(set(eng_vocab))
eng_vocab.sort()

for word in tel_list_train:
    max_tel_len=max(max_tel_len,len(word))
    if(max_tel_len==len(word)):
        max_tel_word=word
    for letter in word:
        tel_vocab.append(letter)
tel_vocab=list(set(tel_vocab))
tel_vocab.sort()

for word in eng_list_valid:
    max_eng_len=max(max_eng_len,len(word))
for word in eng_list_test:
    max_eng_len=max(max_eng_len,len(word))
for word in tel_list_test:
    max_tel_len=max(max_tel_len,len(word))
for word in tel_list_valid:
    max_tel_len=max(max_tel_len,len(word))
print(tel_vocab)
print(eng_vocab)
print(len(max_tel_word))
print(len(max_eng_word))
print(max_tel_len,max_eng_len)

['ం', 'ః', 'అ', 'ఆ', 'ఇ', 'ఈ', 'ఉ', 'ఊ', 'ఋ', 'ఎ', 'ఏ', 'ఐ', 'ఒ', 'ఓ', 'ఔ', 'క', 'ఖ', 'గ', 'ఘ', 'చ', 'ఛ', 'జ', 'ఝ', 'ఞ', 'ట', 'ఠ', 'డ', 'ఢ', 'ణ', 'త', 'థ', 'ద', 'ధ', 'న', 'ప', 'ఫ', 'బ', 'భ', 'మ', 'య', 'ర', 'ఱ', 'ల', 'ళ', 'వ', 'శ', 'ష', 'స', 'హ', 'ా', 'ి', 'ీ', 'ు', 'ూ', 'ృ', 'ె', 'ే', 'ై', 'ొ', 'ో', 'ౌ', '్']
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
21
28
21 28


In [ ]:
# function to convert the telugu or english word to a vectorial representation
def word_to_vector(language,word):
    vec=[]
    if(language=="english"):
        vec.append(len(eng_vocab)+1)
        for letter in word:
            for albt in range(len(eng_vocab)):
                if(eng_vocab[albt]==letter):
                    vec.append(albt+1)
        while(len(vec)<(max_eng_len+1)):
            vec.append(0)
        vec.append(0)
    else:
        vec.append(len(tel_vocab)+1)
        for letter in word:
            for albt in range(len(tel_vocab)):
                if(tel_vocab[albt]==letter):
                    vec.append(albt+1)
        while(len(vec)<(max_tel_len+1)):
            vec.append(0)
        vec.append(0)
    return vec
print(word_to_vector("english",eng_list_train[1]))
print(word_to_vector("telugu",tel_list_train[1]))
print(len(word_to_vector("english",eng_list_train[1])))
print(len(word_to_vector("telugu",tel_list_train[1])))
print(eng_list_train[1])
print(tel_list_train[1])
# print(eng_list_train.shape)
print(len(eng_vocab))
print(len(tel_vocab))

[27, 22, 1, 19, 20, 1, 4, 9, 18, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[63, 45, 48, 62, 30, 50, 32, 51, 41, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
30
23
vastadira
వస్తాదిరా
26
62


In [ ]:
#creation of the matrix for the english and the telugu words

# for training data
eng_matrix_train=[]
for word in eng_list_train:
    eng_matrix_train.append(word_to_vector("english",word))
tel_matrix_train=[]
for word in tel_list_train:
    tel_matrix_train.append(word_to_vector("telugu",word))
eng_matrix_train=torch.tensor(eng_matrix_train)
tel_matrix_train=torch.tensor(tel_matrix_train)
print(eng_matrix_train[1])
print(tel_matrix_train[1])
print(eng_list_train[1])
print(tel_list_train[1])


#for validation data
eng_matrix_valid=[]
tel_matrix_valid=[]
for word in eng_list_valid:
    eng_matrix_valid.append(word_to_vector("english",word))
for word in tel_list_valid:
    tel_matrix_valid.append(word_to_vector("telugu",word))
eng_matrix_valid=torch.tensor(eng_matrix_valid)
tel_matrix_valid=torch.tensor(tel_matrix_valid)
print(eng_matrix_valid[1])
print(tel_matrix_valid[1])
print(eng_list_valid[1])
print(tel_list_valid[1])


# for test data
eng_matrix_test=[]
tel_matrix_test=[]
for word in eng_list_test:
    eng_matrix_test.append(word_to_vector("english",word))
for word in tel_list_test:
    tel_matrix_test.append(word_to_vector("telugu",word))
eng_matrix_test=torch.tensor(eng_matrix_test) # converted to tensors for the tensor feasible applications
tel_matrix_test=torch.tensor(tel_matrix_test)
print(eng_matrix_test[1])
print(tel_matrix_test[1])
print(eng_list_test[1])
print(tel_list_test[1])


print(len(eng_matrix_train))
print(len(eng_matrix_valid))
print(len(eng_matrix_test))
print(tel_matrix_train.shape)
print(eng_matrix_train.shape)

tensor([27, 22,  1, 19, 20,  1,  4,  9, 18,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])
tensor([63, 45, 48, 62, 30, 50, 32, 51, 41, 50,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0])
vastadira
వస్తాదిరా
tensor([27, 22,  9, 14, 25,  1, 19,  1,  1, 14, 14,  9,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])
tensor([63, 45, 51, 34, 62, 40, 50, 48, 50, 34, 62, 34, 51,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0])
vinyasaanni
విన్యాసాన్ని
tensor([27, 16, 18,  1, 25,  1,  1, 14,  9, 11, 21, 12, 21,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])
tensor([63, 35, 62, 41, 40, 50, 29, 51, 16, 53, 43, 53,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0])
prayaanikulu
ప్రయాణికులు
51200
4096
4096
torch.Size([51200, 23])
torch.Size([51200, 30])


In [ ]:
# encoder class for the input and producing the output as the input for the decoder
class Encoder(nn.Module):
    def __init__(self,input_size,embedding_size,enc_layers,hidden_size,cell_type,bi_directional_bit,dropout):
        super(Encoder,self).__init__()
        self.input_size=input_size
        self.embedding_size=embedding_size
        self.enc_layers=enc_layers
        self.dec_layers=dec_layers
        self.cell_type=cell_type
        self.bi_directional_bit=bi_directional_bit
        self.dropout=nn.Dropout(dropout)
        self.embedding=nn.Embedding(input_size,embedding_size)
        self.hidden_size=hidden_size
        self.batch_size=batch_size
        #based on the type of the cell considering the variant of the neural network to be used
        if(cell_type=="RNN"):
            self.rnn=nn.RNN(embedding_size,hidden_size,enc_layers,dropout=dropout,bidirectional=bi_directional_bit)
        elif(cell_type=="GRU"):
            self.gru=nn.GRU(embedding_size,hidden_size,enc_layers,dropout=dropout,bidirectional=bi_directional_bit)
        else:
            self.lstm=nn.LSTM(embedding_size,hidden_size,enc_layers,dropout=dropout,bidirectional=bi_directional_bit)



    #forward passing
    def forward(self,x,hidden,cell):
        embedding=self.embedding(x).view(-1,self.batch_size,self.embedding_size)
        embedding=self.dropout(embedding) # adding the dropout at the input layer
        if(cell_type=="RNN"):
            output,hidden=self.rnn(embedding,hidden)
        elif(cell_type=="GRU"):
            output,hidden=self.gru(embedding,hidden)
        else:
            output,(hidden,cell)=self.lstm(embedding,(hidden,cell))
            return output,hidden,cell
        return output,hidden

    # initialize the tensor to zeroes at start
    def initialize_hidden(self):
        if(self.bi_directional_bit==True):
            return torch.zeros(2*self.enc_layers,self.batch_size,self.hidden_size,device=device)
        return torch.zeros(self.enc_layers,self.batch_size,self.hidden_size,device=device)
    def initialize_cell(self):
        if(self.bi_directional_bit==True):
            return torch.zeros(2*self.enc_layers,self.batch_size,self.hidden_size,device=device)
        return torch.zeros(self.enc_layers,self.batch_size,self.hidden_size,device=device)

In [ ]:
#declearing the decoder class
class Decoder(nn.Module):
    def __init__(self,input_size,embedding_size,hidden_size,dec_layers,dropout,cell_type,output_size):
        super(Decoder,self).__init__()
        self.input_size=input_size
        self.embedding_size=embedding_size
        self.hidden_size=hidden_size
        self.dec_layers=dec_layers
        self.dropout=nn.Dropout(dropout)
        self.cell_type=cell_type
        self.embedding=nn.Embedding(input_size,embedding_size)
        if(cell_type=="RNN"):
            self.rnn=nn.RNN(embedding_size,hidden_size,dec_layers,dropout=dropout)
        elif(cell_type=="GRU"):
            self.gru=nn.GRU(embedding_size,hidden_size,dec_layers,dropout=dropout)
        else:
            self.lstm=nn.LSTM(embedding_size,hidden_size,dec_layers,dropout=dropout)
        self.fully_conc=nn.Linear(hidden_size,output_size)

    # forward pass
    def forward(self,x,prev_output,prev_hidden,cell=0):
        x=x.unsqueeze(0).int() # convert the input token X to tensor and gives a single dimension
        embedding=self.embedding(x)
        embedding=self.dropout(embedding)
        if(cell_type=="RNN"):
            outputs,hidden=self.rnn(embedding,prev_hidden)
        elif(cell_type=="GRU"):
            outputs,hidden=self.gru(embedding,prev_hidden)
        else:
            outputs,(hidden,cell)=self.lstm(embedding,(prev_hidden,cell))

        #as we converted it by using unsqueezing the dimension of the output is like(1,N,hidden_size)
        pred=self.fully_conc(outputs)
        # this makes the dimension as the (1,N,size_of_vocab)
        pred=pred.squeeze(0)
        # this makes the dimension as the (N,size_of_vocab)
        if(cell_type=="GRU" or cell_type == "RNN"):
            return pred,hidden
        return pred,hidden,cell


    #initialize the tensor to zeroes
    def initialize_hidden(self):
        return torch.zeros(self.dec_layers,self.batch_size,self.hidden_size,device=device)

In [ ]:
class attention_add_decoder(nn.Module):
    def __init__(self,input_size,embedding_size,hidden_size,output_size,cell_type,dec_layers,dropout,bi_directional_bit):
        super(attention_add_decoder,self).__init__()
        self.input_size=input_size
        self.hidden_size=hidden_size
        self.output_size=output_size
        self.cell_type=cell_type
        self.dec_layers=dec_layers
        self.bi_directional_bit=bi_directional_bit
        self.cell_type=cell_type
        self.embedding_size=embedding_size
        self.dropout=nn.Dropout(dropout)
        self.length=len(eng_matrix_train[0])
        self.embedding=nn.Embedding(input_size,embedding_size)
        if(self.cell_type=="LSTM"):
            self.lstm=nn.LSTM(hidden_size,hidden_size,dec_layers,dropout=dropout)
        elif(self.cell_type=="GRU"):
            self.gru=nn.GRU(hidden_size,hidden_size,dec_layers,dropout=dropout)
        else:
            self.rnn=nn.RNN(hidden_size,hidden_size,dec_layers,dropout=dropout)
        self.fully_conc=nn.Linear(hidden_size,output_size)
        self.attention=nn.Linear(hidden_size+embedding_size,self.length)
        if(bi_directional_bit==True):
            self.atten_adding=nn.Linear(hidden_size*2+embedding_size,hidden_size)
        elif(bi_directional_bit==False):
            self.atten_adding=nn.Linear(hidden_size+embedding_size,hidden_size)

    def forward(self,x,prev_output,prev_hidden,cell=0):
        prev_output = prev_output.permute(1,0,2) #this will help to rearrange the dimensions to 1,0,2
        x=x.unsqueeze(0)
        embedded=self.dropout(self.embedding(x))
        cnct=torch.cat((embedded[0],prev_hidden[0]),1)
        atten_parameters=func.softmax(self.attention(cnct),dim=1)
        atten_added=torch.bmm(atten_parameters.unsqueeze(1),prev_output) # this performs a batch wise matrix multiplications4
        atten_added=atten_added.squeeze(1)
#         print("Hello")
#         print("shape of embedded[0] is: ",embedded[0].shape)
#         print("shape of atten_added is: ",atten_added.shape)
        final_output=torch.cat((embedded[0],atten_added),1)
        final_output=torch.unsqueeze(self.atten_adding(final_output),0)
        final_output=func.relu(final_output)

        if(cell_type=="RNN"):
            outputs,hidden=self.rnn(final_output,prev_hidden)
        elif(cell_type=="GRU"):
            outputs,hidden=self.gru(final_output,prev_hidden)
        else:
            outputs,(hidden,cell)=self.lstm(final_output,(prev_hidden,cell))

        pred= self.fully_conc(outputs)
        pred= pred.squeeze(0)
        if(self.cell_type=="GRU" or self.cell_type=="RNN"):
            return pred,hidden
        else:
            return pred,hidden,cell

In [ ]:
class Seq_to_seq(nn.Module):
    def __init__(self,decoder,encoder,cell_type,bidirectional_bit,encoder_layers,decoder_layers):
        super(Seq_to_seq,self).__init__()
        self.decoder=decoder
        self.encoder=encoder
        self.cell_type=cell_type
        self.bidirectional_bit=bidirectional_bit
        self.encoder_layers=encoder_layers
        self.decoder_layers=decoder_layers

    #forward pass
    def forward(self,input_seq,target,teacher_force_ratio=0.5):
        batch_size=input_seq.shape[1]
        tar_seq_length=target.shape[0]
        final_target_vocab_size=len(tel_vocab)+2 #this +2 will help the model for the additional special tokens
        outputs=torch.zeros(tar_seq_length,batch_size,final_target_vocab_size).to(device=device)
        hidden=self.encoder.initialize_hidden()
        cell=self.encoder.initialize_cell()
        if(self.cell_type=="RNN" or self.cell_type=="GRU"):
            encoder_output,hidden=self.encoder(input_seq,hidden,cell)
        else:
            encoder_output,hidden,cell=self.encoder(input_seq,hidden,cell)
        if(self.decoder_layers!=self.encoder_layers or self.bidirectional_bit):
            if(self.cell_type=="RNN" or self.cell_type=="GRU"):
                hidden=hidden[self.encoder_layers-1]+hidden[self.encoder_layers-1]
                hidden=hidden.repeat(self.decoder_layers,1,1)
            if(self.cell_type=="LSTM"):
                cell=cell[self.encoder_layers-1]+cell[self.encoder_layers-1]
                cell=cell.repeat(self.decoder_layers,1,1)
        x=target[0]
        for t in range(1,tar_seq_length):
            if(cell_type=="RNN" or cell_type=="GRU"):
                output,hidden=self.decoder(x,encoder_output,hidden)
            else:
                output,hidden,cell=self.decoder(x,encoder_output,hidden,cell)
            outputs[t]=output
            predicted=output.argmax(1)
            if(random.random()<teacher_force_ratio):
                x=target[t]
            else:
                x=predicted
        return outputs

In [ ]:
def recurrent_neural_network(cell_type, bi_directional_bit, embedding_size, enc_dropout, dec_dropout, enc_layers, dec_layers, hidden_size, batch_size, attention, learning_rate, max_epochs,attention_bit):
    enc_input_size=len(eng_vocab)+2
    dec_input_size=len(tel_vocab)+2
    output_size=len(tel_vocab)+2
    # encoder network decleration
    encoder_section=Encoder(enc_input_size,embedding_size,enc_layers,hidden_size,cell_type,bi_directional_bit,enc_dropout).to(device=device)
    # decoder network decleration
    if(attention_bit):
        decoder_section=attention_add_decoder(dec_input_size,embedding_size,hidden_size,output_size,cell_type,dec_layers,dec_dropout,bi_directional_bit).to(device=device)
    else:
        decoder_section=Decoder(dec_input_size,embedding_size,hidden_size,dec_layers,dec_dropout,cell_type,output_size).to(device=device)
    model=Seq_to_seq(decoder_section,encoder_section,cell_type,bi_directional_bit,enc_layers,dec_layers)
    optimizer=optim.Adam(model.parameters(),lr=learning_rate)
    pad = len(tel_vocab)+1
    loss_criterion=nn.CrossEntropyLoss(ignore_index=pad)
#     print(batch_size)
    for itr in range(max_epochs):
        print("epoch: ",itr)

        model.train()
        final_loss=0
        step=0
        for batch_id in tqdm(range((int)(len(eng_matrix_train)/batch_size))):
            inp_word=eng_matrix_train[batch_size*batch_id:batch_size*(batch_id+1)].to(device=device)
            out_word=tel_matrix_train[batch_size*batch_id:batch_size*(batch_id+1)].to(device=device)
            out_word=out_word.T
            inp_word=inp_word.T
            output=model(inp_word,out_word)

            output=output[1:].reshape(-1,output.shape[2])
            out_word=out_word[1:].reshape(-1)
            optimizer.zero_grad()
            loss=loss_criterion(output,out_word)
            final_loss=final_loss+loss;
            loss.backward()

            torch.nn.utils.clip_grad_norm(model.parameters(),max_norm=1)
            optimizer.step()
            step=step+1
        print("total loss: ",final_loss/step)
        print("train accuracy: ",accuracy_fun(eng_matrix_train,tel_matrix_train,batch_size,max_epochs,model))
        print("valid accuracy: ",accuracy_fun(eng_matrix_valid,tel_matrix_valid,batch_size,max_epochs,model))
        print("test accuracy: ",accuracy_fun(eng_matrix_test,tel_matrix_test,batch_size,max_epochs,model))


In [ ]:
def accuracy_fun(eng_matrix,tel_matrix,batch_size,max_epochs,model):
    correct=0
#     print(batch_size)
#     print(len(eng_matrix))
    for batch_id in range((int)(len(eng_matrix)/batch_size)):
        inp_word=eng_matrix[batch_size*batch_id:batch_size*(batch_id+1)].to(device=device)
        out_word=tel_matrix[batch_size*(batch_id):batch_size*(batch_id+1)].to(device=device)
        inp_word=inp_word.T
        out_word=out_word.T
        output=model.forward(inp_word,out_word,0)
        output=nn.Softmax(dim=2)(output)
        output=torch.argmax(output,dim=2)
#         print(batch_id)
#         print(batch_id,output)
        output=output.T
#         print(output)
        out_word=out_word.T
        for i in range(batch_size):
#             print(output[batch_id*batch_size+i],tel_list_train[batch_id*batch_size+i])
#             print(output[i],out_word[i])
            if(torch.equal(output[i][1:],out_word[i][1:])):
                correct=correct+1
#                 print('hello',output[i][1:],out_word[i][1:])
    return ((correct*100)/len(eng_matrix));

In [ ]:
bi_directional_bit=True
enc_layers=3
dec_layers=3
batch_size=512
embedding_size=256
hidden_size=512
enc_dropout=0
dec_dropout=0
max_epochs=60
learning_rate=1e-3
cell_type='GRU'
attention_bit=True
recurrent_neural_network(cell_type, bi_directional_bit, embedding_size, enc_dropout, dec_dropout, enc_layers, dec_layers, hidden_size, batch_size, attention, learning_rate, max_epochs,attention_bit)

epoch:  0


  0%|          | 0/100 [00:00<?, ?it/s]/tmp/ipykernel_34/3514724418.py:37: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  torch.nn.utils.clip_grad_norm(model.parameters(),max_norm=1)
100%|██████████| 100/100 [00:54<00:00,  1.85it/s]


total loss:  tensor(1.5785, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  0.099609375
valid accuracy:  0.5615234375
test accuracy:  0.5859375
epoch:  1


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.7154, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  15.634765625
valid accuracy:  20.99609375
test accuracy:  18.8232421875
epoch:  2


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.3195, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  42.16015625
valid accuracy:  40.8935546875
test accuracy:  37.9638671875
epoch:  3


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.2045, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  54.01171875
valid accuracy:  46.6796875
test accuracy:  43.7255859375
epoch:  4


100%|██████████| 100/100 [00:53<00:00,  1.87it/s]


total loss:  tensor(0.1417, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  62.0078125
valid accuracy:  48.779296875
test accuracy:  45.7763671875
epoch:  5


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.1175, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  67.01953125
valid accuracy:  51.26953125
test accuracy:  47.5830078125
epoch:  6


100%|██████████| 100/100 [00:53<00:00,  1.87it/s]


total loss:  tensor(0.0880, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  73.65625
valid accuracy:  53.8818359375
test accuracy:  49.8779296875
epoch:  7


100%|██████████| 100/100 [00:53<00:00,  1.87it/s]


total loss:  tensor(0.0817, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  76.572265625
valid accuracy:  53.9794921875
test accuracy:  49.2919921875
epoch:  8


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.0627, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  80.3828125
valid accuracy:  54.39453125
test accuracy:  49.365234375
epoch:  9


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.0509, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  79.416015625
valid accuracy:  53.1982421875
test accuracy:  47.75390625
epoch:  10


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.0475, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  84.0625
valid accuracy:  56.2255859375
test accuracy:  51.513671875
epoch:  11


100%|██████████| 100/100 [00:53<00:00,  1.87it/s]


total loss:  tensor(0.0431, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  88.65625
valid accuracy:  55.6884765625
test accuracy:  51.0498046875
epoch:  12


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  90.7421875
valid accuracy:  56.201171875
test accuracy:  51.904296875
epoch:  13


100%|██████████| 100/100 [00:53<00:00,  1.87it/s]


total loss:  tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  89.01953125
valid accuracy:  55.37109375
test accuracy:  51.416015625
epoch:  14


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  90.8515625
valid accuracy:  56.591796875
test accuracy:  52.8076171875
epoch:  15


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  92.986328125
valid accuracy:  57.470703125
test accuracy:  53.2958984375
epoch:  16


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  93.28515625
valid accuracy:  56.689453125
test accuracy:  52.1484375
epoch:  17


100%|██████████| 100/100 [00:53<00:00,  1.88it/s]


total loss:  tensor(0.0154, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  95.109375
valid accuracy:  57.4462890625
test accuracy:  52.685546875
epoch:  18


100%|██████████| 100/100 [00:53<00:00,  1.87it/s]


total loss:  tensor(0.0142, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  93.869140625
valid accuracy:  56.93359375
test accuracy:  52.978515625
epoch:  19


100%|██████████| 100/100 [00:53<00:00,  1.87it/s]


total loss:  tensor(0.0113, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  96.607421875
valid accuracy:  58.3740234375
test accuracy:  52.6123046875
epoch:  20


100%|██████████| 100/100 [00:52<00:00,  1.89it/s]


total loss:  tensor(0.0099, device='cuda:0', grad_fn=<DivBackward0>)
train accuracy:  97.388671875
valid accuracy:  59.66796875
test accuracy:  53.466796875
epoch:  21


 99%|█████████▉| 99/100 [00:52<00:00,  1.86it/s]